CREATE TABLE LAB1$EXAM (
Student_id INTEGER NOT NULL,
Result VARCHAR(8) NOT NULL,
Mark1	INTEGER NULL,
Mark2	INTEGER NULL,
Mark3	INTEGER NULL,
Mark4	INTEGER NULL
);

ALTER TABLE LAB1$EXAM
ADD(PRIMARY KEY(Student_id, Result));

CREATE TABLE LAB1$STIPEN (
Prcnt	INTEGER NULL,
Result	VARCHAR(8) NOT NULL
);

ALTER TABLE LAB1$STIPEN
ADD	(PRIMARY KEY (Result)); 

CREATE TABLE LAB1$STUDENT (
Student_id	INTEGER NOT NULL,
Surname	VARCHAR(20) NULL, 
Name VARCHAR(20) NULL,
Sex	VARCHAR(4) NULL,
Grup VARCHAR(7) NULL
);


ALTER TABLE	LAB1$STUDENT	
ADD	(PRIMARY KEY(Student_id));

ALTER TABLE	LAB1$EXAM		
ADD	(FOREIGN KEY(Result) REFERENCES LAB1$STIPEN) ;

ALTER TABLE	LAB1$EXAM		
ADD	(FOREIGN KEY(Student_id)REFERENCES LAB1$STUDENT) ;
