CREATE TABLE PME_DATA_REFRESH_JOBS
(
  REFRESH_TYPE              VARCHAR2(20),
  DATA_CHANGE_AUDIT_VIEW    VARCHAR2(30) NOT NULL,
  JOB_ASSIGNMENT_TABLE      VARCHAR2(30) NOT NULL,
  ERROR_LOG_TABLE           VARCHAR2(30),
  BATCH_SIZE                NUMBER(10)   NOT NULL,
  MAX_NUM_OF_SLAVES         NUMBER(2)    NOT NULL,
  SLEEP_TIME_IN_SECONDS     NUMBER(5),
  OVERLAP_SECONDS           NUMBER(3) DEFAULT 0 NOT NULL,
  SIGNAL                    VARCHAR2(5)  NOT NULL,
  LAST_PROCESSED_CHANGE_TS  TIMESTAMP(6) DEFAULT TIMESTAMP '2000-01-01 00:00:00' NOT NULL,
  UPDATE_DTIME              DATE         DEFAULT SYSDATE NOT NULL,
  PROC_ID                   NUMBER(20),
  BEFORE_PROC               VARCHAR2(61),
  AFTER_PROC                VARCHAR2(61),
  MAX_NUM_OF_JOBS           NUMBER(3) DEFAULT 0,
  CONSTRAINT CHK_DATA_REFRESH_JOB_SIGNAL CHECK (signal IN ('STOP','START')),
  CONSTRAINT PK_PME_DATA_REFRESH_JOBS PRIMARY KEY (REFRESH_TYPE)
);

CREATE TABLE PME_DATA_REFRESH_LIST
(
  REFRESH_TYPE  VARCHAR2(20),
  NUM           NUMBER(3),
  OPERATION     VARCHAR2(10),
  TGT           VARCHAR2(30) NOT NULL,
  SRC           VARCHAR2(30) NOT NULL,
  ERR           VARCHAR2(30),
  WHR           VARCHAR2(256),
  COMMIT_AT     NUMBER(10) DEFAULT 0 NOT NULL,
  BATCH_NUM     NUMBER(2) DEFAULT 1 NOT NULL,
  AS_JOB        CHAR(1) DEFAULT 'N' NOT NULL,
  HINT          VARCHAR2(500),
  CONSTRAINT CHK_DATA_REFRESH_LIST_AS_JOB CHECK (as_job IN ('Y','N')),
  CONSTRAINT CHK_DATA_REFRESH_LIST_OPER CHECK (operation IN ('INSERT','UPDATE','APPEND','MERGE','REPLACE','EQUALIZE','DELETE','PROCEDURE', 'WAIT')),
  CONSTRAINT PK_PME_DATA_REFRESH_LIST PRIMARY KEY(REFRESH_TYPE, BATCH_NUM, NUM),
  CONSTRAINT FK_DATA_REFRESH_LST_TYPE FOREIGN KEY (REFRESH_TYPE) REFERENCES FUSION.PME_DATA_REFRESH_JOBS (REFRESH_TYPE) ON DELETE CASCADE  
);

CREATE TABLE PME_DATA_REFRESH_ERROR_STATS
(
  REFRESH_TYPE   VARCHAR2(20),
  ERR_TABLE      VARCHAR2(30),
  ERR_MESSAGE    VARCHAR2(2000),
  NEW_COUNT      NUMBER(10) NOT NULL,
  OLD_COUNT      NUMBER(10) DEFAULT 0 NOT NULL,
  UPDATE_DT      DATE DEFAULT SYSDATE NOT NULL,
  OLD_UPDATE_DT  DATE,
  CONSTRAINT PK_PME_DATA_REFRESH_ERR_STATS PRIMARY KEY(REFRESH_TYPE, ERR_TABLE, ERR_MESSAGE),
  CONSTRAINT FK_PME_DRF_ERRSTAT_REFTYPE FOREIGN KEY (REFRESH_TYPE) REFERENCES PME_DATA_REFRESH_JOBS (REFRESH_TYPE) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER bur_pme_data_refresh_err_stats
BEFORE UPDATE ON FUSION.PME_DATA_REFRESH_ERROR_STATS FOR EACH ROW
BEGIN
  :new.old_count := :old.new_count;
  :new.old_update_dt := :old.update_dt;
  :new.update_dt := SYSDATE; 
END;
/
