CREATE OR REPLACE PUBLIC SYNONYM obj_name_value FOR obj_name_value;
CREATE OR REPLACE PUBLIC SYNONYM tab_v256 FOR tab_v256;
CREATE OR REPLACE PUBLIC SYNONYM tab_name_values FOR tab_name_values;
CREATE OR REPLACE PUBLIC SYNONYM xl FOR pkg_dbg_xlogger;
CREATE OR REPLACE PUBLIC SYNONYM dbm FOR PKG_DB_MAINTENANCE;
CREATE OR REPLACE PUBLIC SYNONYM etl FOR pkg_etl_utils;
CREATE OR REPLACE PUBLIC SYNONYM drf FOR pkg_data_refresh;
CREATE OR REPLACE PUBLIC SYNONYM v_table_partition_info FOR v_table_partition_info;